# Generated by Django 4.2 on 2025-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('gpay', 'Google Pay / UPI'), ('paytm', 'Paytm Wallet'), ('card', 'Credit / Debit Card')], max_length=20),
        ),
    ]
