# Generated by Django 4.2 on 2025-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('EV', 'Electric Vehicle')], max_length=12, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['vehicle_type'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('EV', 'Electric Vehicle')], default='SEDAN', max_length=12),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_type',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('EV', 'Electric Vehicle')], default='SEDAN', max_length=12),
        ),
    ]
